const FoodData = [
  {
    id: 1,
    img: "https://img.freepik.com/free-photo/seafood-pizza_74190-5944.jpg?w=996&t=st=1693062328~exp=1693062928~hmac=53fd9ad496580db41c6ca8066510cd89c6b0a0389de8bb6b875a78a1eda09cb5",
    name: "Onion Pizza",
    price: 150,
    desc: "A delicious pizza topped with fresh onions for a delightful flavor combination. This pizza is perfect for onion lovers and offers a unique twist on the classic pizza experience. Enjoy the perfect blend of cheesy goodness and the sharp taste of onions in every bite. Whether you're sharing with friends or enjoying it all to yourself, this Onion Pizza is sure to satisfy your pizza cravings.",
    category: "Pizza",
    rating: 4.5,
  },
  {
    id: 2,
    img: "https://as1.ftcdn.net/v2/jpg/06/08/19/46/1000_F_608194671_BNXAs98uEbTi1OXYHSN3GiVtJPbTIom6.webp",
    name: "Margherita Pizza",
    price: 130,
    desc: "A classic Italian pizza topped with fresh tomatoes, mozzarella cheese, basil leaves, and a drizzle of olive oil. Simple yet bursting with flavors, this Margherita Pizza is a timeless favorite that captures the essence of Italian cuisine.",
    category: "Pizza",
    rating: 4.2,
  },
  {
    id: 3,
    img: "https://freepngimg.com/thumb/pizza/35730-9-pepperoni-pizza-image.png",
    name: "Pepperoni Pizza",
    price: 160,
    desc: "Indulge in the savory delight of this Pepperoni Pizza, loaded with slices of spicy pepperoni, melted cheese, and a tangy tomato sauce. A popular choice that's perfect for satisfying your pizza cravings.",
    category: "Pizza",
    rating: 4.6,
  },
  {
    id: 4,
    img: "https://img.freepik.com/premium-photo/classic-thin-pizza-with-mozzarella-spinach-mushrooms-white-background_555047-3405.jpg?w=740",
    name: "Mushroom and Spinach Pizza",
    price: 140,
    desc: "Experience the earthy flavors of mushrooms combined with the freshness of spinach on this delightful pizza. Topped with a blend of cheeses, this Mushroom and Spinach Pizza offers a balanced and satisfying taste.",
    category: "Pizza",
    rating: 4.2,
  },
  {
    id: 5,
    img: "https://static.vecteezy.com/system/resources/previews/024/108/111/non_2x/tasty-bbq-chicken-cheese-pizza-isolated-on-transparent-background-png.png",
    name: "BBQ Chicken Pizza",
    price: 170,
    desc: "Savor the smoky goodness of this BBQ Chicken Pizza, featuring tender pieces of chicken marinated in barbecue sauce, red onions, and a medley of cheeses. A fusion of flavors that's sure to delight your taste buds.",
    category: "Pizza",
    rating: 4.8,
  },
  {
    id: 6,
    img: "https://i.pinimg.com/564x/ab/32/ac/ab32ac5953c00983c93f8fa8c98a68b1.jpg",
    name: "Classic Pancakes",
    price: 80,
    desc: "Start your day with a stack of fluffy pancakes served with maple syrup and a dollop of butter. A timeless breakfast favorite that's sure to satisfy your morning cravings.",
    category: "Ice cream",
    rating: 4.5,
  },

  {
    id: 8,
    img: "https://www.cfacdn.com/img/order/menu/Online/Sides%26treats/Jul19_OrganicAussieGreekYogurtParfaitCupGranola_pdp.png",
    name: "Greek Yogurt Parfait",
    price: 95,
    desc: "Enjoy a healthy and refreshing breakfast with layers of creamy Greek yogurt, fresh berries, honey, and granola. A balanced option that provides a burst of flavors and energy.",
    category: "Ice cream",
    rating: 4.1,
  },

  {
    id: 10,
    img: "https://pngimg.com/uploads/porridge/porridge_PNG56.png",
    name: "Fruit and Nut Oatmeal",
    price: 85,
    desc: "Warm up with a bowl of hearty oatmeal packed with mixed fruits, nuts, and a drizzle of honey. A wholesome breakfast that provides a satisfying start to your day.",
    category: "Healthy Foods",
    rating: 4.5,
  },

  {
    id: 13,
    img: "https://www.seekpng.com/png/full/760-7608020_go-to-image-stir-fry-vegetables-transparent.png",
    name: "Vegetable Stir-Fry",
    price: 130,
    desc: "Enjoy a medley of colorful vegetables stir-fried in a flavorful sauce, served over steamed rice. A light and nutritious dinner that's both satisfying and wholesome.",
    category: "Healthy Foods",
    rating: 4.2,
  },
  {
    id: 31,
    img: "https://myheartbeets.com/wp-content/uploads/2013/08/indian-egg-curry.jpg",
    name: "Egg Curry",
    price: 190,
    desc: "A popular comfort food rich in nutrients like calcium, proteins, vitamins, and minerals, making it a wholesome side dish.",
    category: "Healthy Foods",
    rating: 4.4,
  },
  {
    id: 32,
    img: "https://headbangerskitchen.com/wp-content/uploads/2022/07/TANDOORICHICKEN-H4.jpg",
    name: "Tandoori Chicken",
    price: 220,
    desc: "A delicious and healthy dish high in protein, perfect for gaining muscle mass and satisfying your taste buds.",
    category: "Healthy Foods",
    rating: 4.9,
  },
  {
    id: 33,
    img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/07/chana-dal.jpg.webp",
    name: "Dal",
    price: 120,
    desc: "A low-calorie, protein-rich food with good nutritional values, making it a nutritious and wholesome choice.",
    category: "Healthy Foods",
    rating: 4.7,
  },
  {
    id: 34,
    img: "https://thewanderlustkitchen.com/wp-content/uploads/2019/03/creamy-vegan-tikka-masala_01.jpg",
    name: "Vegetarian Tikka Masala",
    price: 160,
    desc: "A vegan-friendly option packed with healthy veggies, using affordable tinned tomatoes and chickpeas for a delightful flavor.",
    category: "Healthy Foods",
    rating: 4.5,
  },
  {
    id: 35,
    img: "https://veganhuggs.com/wp-content/uploads/2021/04/aloo-gobi-overhead-view.jpg",
    name: "Aloo Gobi",
    price: 140,
    desc: "A traditional vegetarian dish with cauliflower, potatoes, and Indian spices, offering fiber, antioxidants, and aiding digestion.",
    category: "Healthy Foods",
    rating: 4.6,
  },
  {
    id: 36,
    img: "https://images.immediate.co.uk/production/volatile/sites/2/2022/06/OLI-Christmas2019-EverydaySpinachChickpeaPotatoCurry-65d814a.jpg?quality=90&webp=true&resize=375,341",
    name: "Potato Chickpea Curry",
    price: 170,
    desc: "A nutrient-rich curry with protein, fiber, iron, and vitamins. Chickpeas are low in fat and high in protein.",
    category: "Healthy Foods",
    rating: 4.3,
  },
  {
    id: 41,
    img: "https://www.theroastedroot.net/wp-content/uploads/2023/06/dairy-free-vanilla-ice-cream-8-800x1200.jpg",
    name: "Vanilla Ice Cream",
    price: 80,
    desc: "Indulge in the classic and creamy Vanilla Ice Cream, a timeless treat that satisfies your sweet cravings. Perfect for any occasion!",
    category: "Ice cream",
    rating: 4.8,
  },
  {
    id: 42,
    img: "https://afoodloverskitchen.com/wp-content/uploads/chocolate-chocolate-chip-ice-cream-t1-scaled.jpg",
    name: "Chocolate Chip Ice Cream",
    price: 100,
    desc: "Enjoy the delightful combination of rich chocolate ice cream with generous swirls of chocolate chips. A decadent choice for chocolate lovers.",
    category: "Ice cream",
    rating: 4.7,
  },
  {
    id: 43,
    img: "https://www.recipetineats.com/wp-content/uploads/2018/07/Strawberry-Ice-Cream-No-Churn_3b.jpg",
    name: "Strawberry Ice Cream",
    price: 90,
    desc: "Experience the refreshing taste of Strawberry Ice Cream, made with real strawberries for a burst of fruity goodness in every bite.",
    category: "Ice cream",
    rating: 4.6,
  },
  {
    id: 44,
    img: "https://www.scotchandscones.com/wp-content/uploads/2022/07/mango-sorbet-bowl.jpg",
    name: "Mango Sorbet",
    price: 120,
    desc: "Savor the tropical flavor of Mango Sorbet, a dairy-free and refreshing option made with ripe mangoes. A guilt-free indulgence on a hot day.",
    category: "Ice cream",
    rating: 4.9,
  },
  {
    id: 45,
    img: "https://assets.epicurious.com/photos/55d4a46e63b1ba1b5534af4f/1:1/w_1920,c_limit/51100400_hires_CP.jpg",
    name: "Caramel Swirl Ice Cream",
    price: 110,
    desc: "Treat yourself to the luscious Caramel Swirl Ice Cream, featuring velvety caramel ribbons in a smooth and creamy base. A luxurious dessert choice.",
    category: "Ice cream",
    rating: 4.5,
  },
  {
    id: 46,
    img: "https://handletheheat.com/wp-content/uploads/2020/06/Chocolate-Chip-Cookie-Dough-Ice-Cream-SQUARE.jpg",
    name: "Cookie Dough Ice Cream",
    price: 130,
    desc: "Experience the joy of Cookie Dough Ice Cream, filled with chunks of cookie dough in a sweet and creamy base. A delightful blend of textures and flavors.",
    category: "Ice cream",
    rating: 4.7,
  },
];
export default FoodData;
